-- baza danych: firma

-- Napisz zapytanie działające na tabelach bazy danych firma, które:

-- Wyświetla nazwisko, wiek oraz roczne pobory pracownika posortowane wg poborów oraz nazwiska (pole pobory w tabeli pracownicy określa pobory miesięczne).
-- Wyświetla nazwisko, imię, datę urodzenia, stanowisko, dział i pobory pracownika, który pracuje na stanowisku robotnik lub analityk i zarabia więcej niż 2000 miesięcznie.
-- Wyświetla nazwiska i imiona pracowników, którzy zarabiają więcej niż zarabia Adam Kowalik.
-- Podnosi zarobki o 10% na stanowisku robotnik.
-- Oblicza średnie zarobki oraz ilość pracowników na poszczególnych stanowiskach z wyłączeniem stanowisk kierownik.